# Generated by Django 4.1.3 on 2022-11-24 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('issue_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issue_title', models.CharField(max_length=200)),
                ('issue_description', models.TextField()),
                ('issue_type', models.CharField(choices=[('Bug', 'Bug'), ('Task', 'Task'), ('Story', 'Story'), ('Epic', 'Epic')], default='pending', max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschema.project')),
            ],
        ),
    ]
