# Generated by Django 4.1.3 on 2022-11-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myschema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('assigned_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_title', models.CharField(max_length=200)),
                ('assigned_band', models.CharField(choices=[('B6', 'B6'), ('B5L', 'B5L'), ('B7', 'B7'), ('B5', 'B5'), ('B4', 'B4')], default='pending', max_length=50)),
                ('Issues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschema.issues')),
            ],
        ),
    ]
