# Generated by Django 4.1.3 on 2022-11-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myschema', '0002_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('author', models.CharField(default='pending', max_length=50, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('issue1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschema.issues')),
            ],
        ),
    ]
