# Generated by Django 4.1.3 on 2022-11-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschema', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='issue1',
            new_name='Issue1',
        ),
    ]
